# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-05 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionId', models.AutoField(db_column='QuestionID', max_length=1000, primary_key=True, serialize=False)),
                ('Question', models.CharField(blank=True, db_column='question', max_length=1000)),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='UID', max_length=500, primary_key=True, serialize=False)),
                ('UserName', models.CharField(db_column='username', max_length=50)),
                ('Password', models.CharField(db_column='password', max_length=50)),
                ('Phone', models.CharField(db_column='phone', max_length=15)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
    ]
