# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-05 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(db_column='AnswerID', max_length=1000, primary_key=True, serialize=False)),
                ('Answer', models.CharField(blank=True, db_column='answer', max_length=1000)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zhihu.Questions')),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
    ]
