# Generated by Django 2.0 on 2018-01-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0002_auto_20180104_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='UID', max_length=500, primary_key=True, serialize=False)),
                ('UserName', models.CharField(db_column='username', max_length=50)),
                ('Password', models.CharField(db_column='password', max_length=50)),
                ('Phone', models.CharField(db_column='phone', max_length=15)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
